# Generated by Django 4.2.2 on 2023-06-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_post_comments_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='EventComments',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='EventLikes',
        ),
    ]
