# Generated by Django 4.2.2 on 2023-06-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_comments_eventcomments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventComments',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='EventLikes',
            new_name='Likes',
        ),
    ]
