# Generated by Django 4.2.2 on 2023-06-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_eventcomments_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='EventComments',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='EventLikes',
        ),
    ]
