# Generated by Django 4.2.2 on 2023-06-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.DeleteModel(
            name='SportType',
        ),
        migrations.AlterField(
            model_name='eventcomments',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='participation',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sport'),
        ),
        migrations.AddField(
            model_name='event',
            name='sports',
            field=models.ManyToManyField(through='events.Participation', to='events.sport'),
        ),
    ]
