# Generated by Django 4.2.2 on 2023-06-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='pos',
            new_name='post',
        ),
    ]
